name: game_on_flutter
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # This helps to identify if network is available or not.
  connectivity_plus: ^3.0.2

  # Plugin used to inject getX plugin.
  # GetX provided powerful feature for the application such as state management,
  # dependency injection, and route management.
  get: ^4.6.5

  # Shows loader top of the screen to prevent any action to the application while loader is present.
  loader_overlay: ^2.1.0

  # Cache image and load them from cache storage.
  cached_network_image: ^3.2.2

  # Helps to manage platform permission.
  permission_handler: ^10.2.0

  # This shows app notification bar on the top.
  another_flushbar: ^1.12.29

  # Local Notifications
  flutter_local_notifications: ^13.0.0

  # Logger
  logger: ^1.1.0

  # Uses to provide animated loader which is used by loader_overlay plugin.
  flutter_spinkit: ^5.1.0

  # Adds firebase analytics
  firebase_analytics: ^10.4.2
  firebase_core: ^2.1.1
  firebase_messaging: ^14.0.4
  firebase_auth: ^4.1.3
  cloud_firestore: ^4.1.0

  # Get cli
  get_cli: ^0.2.30

  #multiple fab button
  flutter_expandable_fab: ^2.0.0

  # Percent Indicator
  percent_indicator: ^4.2.3

  # Flutter SVG
  flutter_svg: ^2.0.5

  # Easy Rich Text
  easy_rich_text: '^2.0.0'

  # Gets device information which the application is running.
  device_info_plus: ^9.0.2

  # Image picker
  image_picker: ^0.8.3+2

  # Animations
  animations: ^2.0.7

  # Enable pin input for enter otp.
  pin_code_fields: ^7.1.0

  # Dio networking library
  dio: ^5.2.0+1

  # Dio api call interceptor used for show formatted request
  # and response logs in the console.
  awesome_dio_interceptor: ^1.0.0

  # rounded checkbox widget.
  roundcheckbox: ^2.0.5

  # dotted border
  dotted_border: ^2.0.0

  # flutter slideable
  flutter_slidable: ^3.0.0

  # Url Launcher
  url_launcher: ^6.1.11

  # collection
  collection: ^1.17.0

  # group list
  grouped_list: ^5.1.2

  # shimmer
  shimmer: ^3.0.0

  # Extension library of GetX. It allows to store session inside of the app.
  get_storage: ^2.0.3

  # google places
  flutter_google_places: ^0.3.0

  # intl for date operations
  intl: ^0.18.1

  # Chip choice
  chips_choice: ^3.0.0

  # expansion tile
  expansion_tile_card: ^3.0.0

  # expandable
  expandable: ^5.0.1

  # like_button
  like_button: ^2.0.5

  # auto complete textfield
  autocomplete_textfield: ^2.0.1

  # drop down button
  dropdown_button2: ^2.1.4

  # group button
  group_button: ^5.3.0

  # lottie
  lottie: ^2.3.2

  # load more
  loadmore: ^2.0.1

  # Package info plus
  package_info_plus: ^3.0.3

  # emoji picker flutter
  emoji_picker_flutter: ^1.6.1

  # Keyboard visibility tracker
  flutter_keyboard_visibility: ^5.4.1

  # location
  location: ^4.2.0

  # dart ipify
  dart_ipify: ^1.1.1

  # geocoder
  geocoder2: ^1.4.0

  # share plus
  share_plus: ^7.0.2

  #animated switch
  animated_switch: ^0.0.2

  # google map flutter
  google_maps_flutter: ^2.2.7

  # auto scale tabbar view.
  autoscale_tabbarview: ^1.0.2

  # floating multiple FAbs.
  hawk_fab_menu: ^1.2.0

  # expandable page view
  expandable_page_view: ^1.0.17

  # jiffy for date format
  jiffy: ^6.2.1

  # image cropper
  image_cropper: ^4.0.0

  # dropdown search
  dropdown_search: ^5.0.6

  # Get_it DI
  get_it: ^7.6.0

  # OS Level plugin
  restart_app: ^1.1.1+1

  # in-app purchase.
  in_app_purchase: ^3.1.7

  # Widget to parce html text.
  flutter_widget_from_html: ^0.10.3

  # infinite scroll pagination
  infinite_scroll_pagination: ^3.2.0

  # hive storage
  hive: ^2.2.3

  # Provider
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/player profile/
    - assets/club image/
    - assets/svg/game_type/
    - assets/svg/user/
    - assets/svg/profile/
    - assets/svg/bottom_nav/
    - assets/svg/post/
    - assets/svg/banner/
    - assets/svg/chat/
    - assets/svg/checkbox/
    - assets/image/
    - assets/image/splash_background/
    - assets/image/sample/
    - assets/image/card/
    - assets/lottie_json/
    - assets/fonts/poppins/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/poppins-light.ttf
          weight: 300
        - asset: assets/fonts/poppins/poppins-regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/poppins-medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/poppins-italic.ttf
          style: italic
        - asset: assets/fonts/poppins/poppins-semi-bold.ttf
          weight: 600
        - asset: assets/fonts/poppins/poppins-bold.ttf
          weight: 700

