// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVjb6O9JQwg584yf1fmM_N9kjFHIhUl-8',
    appId: '1:1022373973149:web:c02f588a514d9d33f35874',
    messagingSenderId: '1022373973149',
    projectId: 'gameon-9ec4a',
    authDomain: 'gameon-9ec4a.firebaseapp.com',
    storageBucket: 'gameon-9ec4a.appspot.com',
    measurementId: 'G-KXCQ4YXJR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe-V8ZfqJtHlTCuP0yeFCnqYHum1WZxfw',
    appId: '1:1022373973149:android:f9aec422fac8772bf35874',
    messagingSenderId: '1022373973149',
    projectId: 'gameon-9ec4a',
    storageBucket: 'gameon-9ec4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg8Sx8-NsF51MjS7NtHE-3cqbtn3AEt00',
    appId: '1:1022373973149:ios:0b5595b1b08340bdf35874',
    messagingSenderId: '1022373973149',
    projectId: 'gameon-9ec4a',
    storageBucket: 'gameon-9ec4a.appspot.com',
    androidClientId: '1022373973149-ckcvcll6uelnm0v2rivjp6lv4p5c1sgf.apps.googleusercontent.com',
    iosClientId: '1022373973149-7fj4u1tsugon9ti83j3lcnmmbk0f10nq.apps.googleusercontent.com',
    iosBundleId: 'com.mobile.gameon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg8Sx8-NsF51MjS7NtHE-3cqbtn3AEt00',
    appId: '1:1022373973149:ios:0b5595b1b08340bdf35874',
    messagingSenderId: '1022373973149',
    projectId: 'gameon-9ec4a',
    storageBucket: 'gameon-9ec4a.appspot.com',
    androidClientId: '1022373973149-ckcvcll6uelnm0v2rivjp6lv4p5c1sgf.apps.googleusercontent.com',
    iosClientId: '1022373973149-7fj4u1tsugon9ti83j3lcnmmbk0f10nq.apps.googleusercontent.com',
    iosBundleId: 'com.mobile.gameon',
  );
}
